name: DevCard

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: devcard
        uses: dailydotdev/action-devcard@2.2.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}

      - name: Replace string in devcard.svg
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: 'charset="utf-8";base64,"'
          replace: 'charset=utf8;base64"'
          include: 'devcard.svg'

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add devcard.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update devcard.svg with new encoding"
          git push
